In [25]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [26]:
##Load the trained model,scaler pickle,onehot
model=load_model('model.h5')

##Load the encoder and scaler
with open ('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [27]:
import pandas as pd

input_data = pd.DataFrame([{
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}])

In [28]:
##One-hot encode 'Geography
geo_encoded =label_encoder_geo.transform(input_data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))

In [29]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [30]:
##combine one-hot encoded columns with input data
input_data = pd.concat(
    [
        input_data.drop("Geography", axis=1),
        geo_encoded_df
    ],
    axis=1
)

In [31]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [32]:
##Encode categorical variable
input_data['Gender']=label_encoder_gender.transform(input_data['Gender'])

In [33]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [35]:
## Scaling the input data
input_scaled=scaler.transform(input_data)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [37]:
##Predict chrun
prediction=model.predict(input_scaled)

1/1 [==============================] - 0s 24ms/step

In [38]:
prediction

array([[0.02925687]], dtype=float32)

In [39]:
prediction_proba = prediction[0][0]

In [41]:
prediction_proba

0.029256865

In [42]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.